---
- name: Install system dependencies
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: 
          - ffmpeg
        state: present
